# Site
title: My Neumorphism Blog
description: A neumorphism-style blog built with Hexo
author: Your Name
language: en

# URL
url: https://example.com
root: /

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories

# Writing
new_post_name: :title.md # File name format for new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in a new tab
filename_case: 0 # 0: preserve, 1: uppercase, 2: lowercase
render_drafts: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: neumorphism